---
- name: run scan
  hosts: all

  tasks:
  - shell: |
      oc login -u kubeadmin -p C6xuJ-345JZ-6d3Vw-Xsffe https://api.crc.testing:6443 --insecure-skip-tls-verify
      oc annotate compliancescans/ocp4-cis compliance.openshift.io/rescan=

