---
- name: run scan
  hosts: all

  tasks:
  - shell: |
      oc login -u kubeadmin -p C6xuJ-345JZ-6d3Vw-Xsffe https://api.crc.testing:6443 --insecure-skip-tls-verify
      oc annotate compliancescans/ocp4-cis compliance.openshift.io/rescan= -n openshift-compliance
      sleep 60
      oc rsync -n openshift-compliance pod/pv-extract:ocp4-scan-results/ ./cis-results
      cd cis-results
      find . -name "*.bzip2" -exec cp {} . \;
      oscap xccdf generate report ocp4-cis-api-checks-pod.xml.bzip2  > ocp4-cis-api-checks-pod.html
      web=$(oc get pods -n web | grep -i "httpd-ex-git" | grep -i running | cut -d' ' -f1)
      oc -n web exec -it $web -- mkdir tmp
      oc -n web cp ocp4-cis-api-checks-pod.html  $web:tmp/
      


      

